use crate::{error::CoreError,model::{ConversionRequest,ConversionResult}};
pub trait ConversionEngine:Send+Sync{fn can_convert(&self,input:crate::format::FileFormat,target:crate::format::FileFormat)->bool;fn convert(&self,r:&ConversionRequest)->Result<ConversionResult,CoreError>;}
pub struct Registry{pub engines:Vec<Box<dyn ConversionEngine>>} impl Registry{pub fn new()->Self{Self{engines:Vec::new()}} pub fn register<E:ConversionEngine+'static>(&mut self,e:E){self.engines.push(Box::new(e));}}

pub fn convert_file(req:&ConversionRequest)->Result<ConversionResult,CoreError>{use std::{fs,path::Path};let src=crate::format::FileFormat::from_path(Path::new(&req.input))?;let raw=fs::read_to_string(&req.input).map_err(|e|CoreError::Io(e.to_string()))?;let text=match (src,req.target){(crate::format::FileFormat::Markdown,crate::format::FileFormat::Txt)=>raw.lines().map(|l|l.trim_start_matches('#').trim().replace("**","")).collect::<Vec<_>>().join("\n"),(crate::format::FileFormat::Html,crate::format::FileFormat::Txt)=>strip_html(&raw),(_,crate::format::FileFormat::Html)=>format!("<!doctype html><meta charset=\"utf-8\"><pre>{}</pre>",escape_html(&raw)),(crate::format::FileFormat::Csv,crate::format::FileFormat::Json)=>csv_to_json(&raw),(crate::format::FileFormat::Json,crate::format::FileFormat::Csv)=>json_to_csv(&raw)?,(a,b) if a==b=>raw,_=>return Err(CoreError::ConversionFailed(format!("unsupported conversion {:?} -> {:?}",src,req.target)))};fs::write(&req.output,&text).map_err(|e|CoreError::Io(e.to_string()))?;Ok(ConversionResult{output:req.output.clone(),bytes_written:text.len() as u64,warnings:vec![]})}
fn escape_html(s:&str)->String{s.replace('&',"&amp;").replace('<',"&lt;").replace('>',"&gt;")}
fn strip_html(s:&str)->String{let mut o=String::new();let mut t=false;for c in s.chars(){if c=='<'{t=true}else if c=='>'{t=false}else if !t{o.push(c)}}o}
fn csv_to_json(s:&str)->String{let mut i=s.lines();let h:Vec<&str>=i.next().unwrap_or("").split(',').collect();let rows:Vec<serde_json::Value>=i.map(|l|{let v:Vec<&str>=l.split(',').collect();let mut m=serde_json::Map::new();for (n,k) in h.iter().enumerate(){m.insert(k.trim().to_string(),serde_json::Value::String(v.get(n).unwrap_or(&"").trim().to_string()));}serde_json::Value::Object(m)}).collect();serde_json::to_string(&rows).unwrap_or_else(|_|"[]".into())}
fn json_to_csv(s:&str)->Result<String,CoreError>{let v:serde_json::Value=serde_json::from_str(s).map_err(|e|CoreError::ConversionFailed(e.to_string()))?;let a=v.as_array().ok_or_else(||CoreError::ConversionFailed("JSON array required".into()))?;if a.is_empty(){return Ok(String::new())}let o=a[0].as_object().ok_or_else(||CoreError::ConversionFailed("JSON objects required".into()))?;let k:Vec<&String>=o.keys().collect();let mut out=k.iter().map(|x|x.to_string()).collect::<Vec<_>>().join(",");for r in a{out.push('\n');out.push_str(&k.iter().map(|x|r.get(*x).map(|z|z.to_string().trim_matches('"').to_string()).unwrap_or_default()).collect::<Vec<_>>().join(","));}Ok(out)}
