import 'package:flutter/material.dart';
void main()=>runApp(const App());
class App extends StatelessWidget{const App({super.key});Widget build(BuildContext c)=>MaterialApp(title:'文档转换器',theme:ThemeData(useMaterial3:true,colorSchemeSeed:Colors.indigo),home:const Shell());}
class Shell extends StatefulWidget{const Shell({super.key});State<Shell> createState()=>_ShellState();}
class _ShellState extends State<Shell>{int i=0;final pages=const [Home(),History(),Settings()];Widget build(BuildContext c)=>Scaffold(body:pages[i],bottomNavigationBar:NavigationBar(selectedIndex:i,onDestinationSelected:(v)=>setState(()=>i=v),destinations:const[NavigationDestination(icon:Icon(Icons.home_outlined),label:'首页'),NavigationDestination(icon:Icon(Icons.history),label:'历史'),NavigationDestination(icon:Icon(Icons.settings_outlined),label:'设置')]));}
class Home extends StatelessWidget{const Home({super.key});Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('文档转换器')),body:Padding(padding:const EdgeInsets.all(20),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[Card(child:Padding(padding:const EdgeInsets.all(24),child:Column(children:[const Icon(Icons.description_outlined,size:56),const SizedBox(height:12),const Text('离线文档转换',style:TextStyle(fontSize:22,fontWeight:FontWeight.bold)),const SizedBox(height:8),const Text('核心转换在本地完成，无需联网'),const SizedBox(height:20),FilledButton.icon(onPressed:()=>showModalBottomSheet(context:c,builder:(_)=>const FormatSheet()),icon:const Icon(Icons.file_open),label:const Text('选择文件'))]))),const SizedBox(height:20),const Text('转换任务',style:TextStyle(fontSize:18,fontWeight:FontWeight.bold)),const Expanded(child:Center(child:Text('暂无任务')))]));}
class FormatSheet extends StatelessWidget{const FormatSheet({super.key});Widget build(BuildContext c)=>SafeArea(child:ListView(padding:const EdgeInsets.all(20),children:[const Text('选择输出格式',style:TextStyle(fontSize:20,fontWeight:FontWeight.bold)),...['PDF','XLSX','CSV','DOCX','PPTX','TXT','HTML','Markdown','PNG'].map((x)=>ListTile(title:Text(x),onTap:()=>Navigator.pop(c)))]));}
class History extends StatelessWidget{const History({super.key});Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('转换历史')),body:const Center(child:Text('暂无历史记录')));}
class Settings extends StatelessWidget{const Settings({super.key});Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('设置')),body:ListView(children:const[ListTile(title:Text('默认输出目录'),subtitle:Text('每次转换时选择')),ListTile(title:Text('默认字体'),subtitle:Text('Noto Sans CJK SC')),ListTile(title:Text('关于'),subtitle:Text('离线文档转换器 0.1.0'))]));}
