import 'dart:convert';
import 'dart:io';
import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';
void main()=>runApp(const App());
class App extends StatelessWidget{const App({super.key});Widget build(BuildContext c)=>MaterialApp(title:'离线文档转换器',theme:ThemeData(useMaterial3:true,colorSchemeSeed:Colors.indigo),home:const Home());}
class Job{final String input;String status;String? output;Job(this.input,this.status);}
class Home extends StatefulWidget{const Home({super.key});State<Home> createState()=>_HomeState();}
class _HomeState extends State<Home>{final jobs=<Job>[];String fmt='TXT';String? dir;bool running=false;
Future<void> pick()async{final r=await FilePicker.platform.pickFiles(allowMultiple:true,type:FileType.custom,allowedExtensions:['txt','md','markdown','csv','json','html','htm']);if(r!=null)setState(()=>jobs.addAll(r.paths.whereType<String>().map((p)=>Job(p,'待转换'))));}
Future<void> chooseDir()async{final d=await FilePicker.platform.getDirectoryPath();if(d!=null)setState(()=>dir=d);}
Future<void> run()async{if(dir==null||jobs.isEmpty)return;setState(()=>running=true);for(final j in jobs){setState(()=>j.status='转换中');try{final src=File(j.input);final text=await src.readAsString();final ext=fmt.toLowerCase()=='markdown'?'md':fmt.toLowerCase();final out='${dir!}/${_base(j.input)}.$ext';await File(out).writeAsString(_convert(text,j.input,fmt));setState((){j.status='成功';j.output=out;});}catch(e){setState(()=>j.status='失败：$e');}}setState(()=>running=false);}
String _base(String p)=>p.split(Platform.pathSeparator).last.split('.').first;
String _convert(String s,String input,String target){final src=input.split('.').last.toLowerCase();if(target=='TXT'){if(src=='html'||src=='htm')return s.replaceAll(RegExp(r'<[^>]*>'),'');if(src=='md'||src=='markdown')return s.replaceAll(RegExp(r'[#*_`]'),'');}if(target=='HTML')return '<!doctype html><meta charset="utf-8"><pre>${const HtmlEscape().convert(s)}</pre>';if(target=='JSON'&&src=='csv'){final lines=s.trim().split(RegExp(r'\r?\n'));if(lines.isEmpty)return '[]';final h=lines.first.split(',');return jsonEncode(lines.skip(1).map((l){final v=l.split(',');return {for(var i=0;i<h.length;i++)h[i].trim():i<v.length?v[i].trim():''};}).toList());}if(target=='CSV'&&src=='json'){final a=jsonDecode(s) as List;if(a.isEmpty)return '';final h=(a.first as Map).keys.toList();return [h.join(','),...a.map((r)=>h.map((k)=>r[k]??'').join(','))].join('\n');}return s;}
Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('离线文档转换器'),actions:[IconButton(onPressed:()=>setState(jobs.clear),icon:const Icon(Icons.delete_sweep))]),body:Padding(padding:const EdgeInsets.all(16),child:Column(children:[Row(children:[Expanded(child:FilledButton.icon(onPressed:pick,icon:const Icon(Icons.file_open),label:const Text('选择文件（可多选）'))),const SizedBox(width:8),IconButton(onPressed:chooseDir,icon:const Icon(Icons.folder),tooltip:'选择输出目录')]),Align(alignment:Alignment.centerLeft,child:Text('输出目录：${dir??'未选择'}')),Row(children:[const Text('格式：'),DropdownButton(value:fmt,items:['TXT','Markdown','CSV','JSON','HTML'].map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:(x)=>setState(()=>fmt=x!))]),SizedBox(width:double.infinity,child:FilledButton(onPressed:running?null:run,child:Text(running?'转换中…':'开始转换'))),Expanded(child:jobs.isEmpty?const Center(child:Text('请选择要转换的文件')):ListView(children:jobs.map((j)=>ListTile(title:Text(j.input.split(Platform.pathSeparator).last),subtitle:Text(j.status),trailing:j.output==null?null:const Icon(Icons.check,color:Colors.green))).toList()))])));}
